import type {
  Archetype,
  GameConfig,
  JobId,
  JobProfile,
  TileDefinition,
} from './types'

export const GAME_SECONDS_PER_TICK = 3
export const TICKS_PER_ROUND = 20
export const BASE_TICK_MS = 1000
export const MAX_LOGS = 48

export const JOBS: Record<JobId, JobProfile> = {
  corporate: {
    id: 'corporate',
    name: 'Corporate',
    tagline: 'High salary, brutal calendar.',
    salary: 190,
    moveCooldown: 3,
    workLock: 6,
    gigBonus: 0,
    stabilityDelta: -4,
  },
  retail: {
    id: 'retail',
    name: 'Retail',
    tagline: 'Predictable enough to survive, flexible enough to move.',
    salary: 125,
    moveCooldown: 2,
    workLock: 3,
    gigBonus: 0.08,
    stabilityDelta: -2,
  },
  creator: {
    id: 'creator',
    name: 'Creator',
    tagline: 'Small floor, big upside, unstable nerves.',
    salary: 105,
    moveCooldown: 2,
    workLock: 1,
    gigBonus: 0.22,
    stabilityDelta: -1,
  },
  freelance: {
    id: 'freelance',
    name: 'Freelance',
    tagline: 'Constant hustle, near-zero guardrails.',
    salary: 88,
    moveCooldown: 1,
    workLock: 0,
    gigBonus: 0.34,
    stabilityDelta: -1,
  },
}

export const TILE_DEFINITIONS: TileDefinition[] = [
  {
    id: 0,
    name: 'Payday Square',
    district: 'Cashflow',
    type: 'start',
    demand: 'medium',
    baseRent: 0,
    growth: 0,
    marketPrice: 0,
    flavor: 'Wrap the board and skim a little oxygen.',
  },
  {
    id: 1,
    name: 'Crash Pad Alley',
    district: 'Outer Ring',
    type: 'property',
    demand: 'low',
    baseRent: 15,
    growth: 0.08,
    marketPrice: 210,
    flavor: 'Cheap enough to enter, expensive enough to sting.',
  },
  {
    id: 2,
    name: 'Co-Living Towers',
    district: 'Sharehouse',
    type: 'property',
    demand: 'medium',
    baseRent: 20,
    growth: 0.11,
    marketPrice: 275,
    flavor: 'The fridge is full of labels and resentment.',
  },
  {
    id: 3,
    name: 'Viral Gig Feed',
    district: 'Feed',
    type: 'event',
    demand: 'medium',
    baseRent: 0,
    growth: 0,
    marketPrice: 0,
    flavor: 'A scroll can wreck you or save you.',
  },
  {
    id: 4,
    name: 'Bushwick Lofts',
    district: 'Hype Zone',
    type: 'property',
    demand: 'high',
    baseRent: 28,
    growth: 0.18,
    marketPrice: 420,
    flavor: 'A nice brick wall for half your paycheck.',
  },
  {
    id: 5,
    name: 'Student Loan Station',
    district: 'Debt Loop',
    type: 'property',
    demand: 'medium',
    baseRent: 22,
    growth: 0.12,
    marketPrice: 305,
    flavor: 'You pay rent and interest in the same breath.',
  },
  {
    id: 6,
    name: 'Luxury Microflat',
    district: 'Vertical City',
    type: 'property',
    demand: 'high',
    baseRent: 32,
    growth: 0.2,
    marketPrice: 470,
    flavor: 'Fits one person and zero hope.',
  },
  {
    id: 7,
    name: 'Mutual Aid Board',
    district: 'Network',
    type: 'event',
    demand: 'low',
    baseRent: 0,
    growth: 0,
    marketPrice: 0,
    flavor: 'Trust still exists, barely.',
  },
  {
    id: 8,
    name: 'Sublet Gardens',
    district: 'Outer Ring',
    type: 'property',
    demand: 'low',
    baseRent: 17,
    growth: 0.09,
    marketPrice: 235,
    flavor: 'The lease is a rumor and the rent is real.',
  },
  {
    id: 9,
    name: 'Algorithm Square',
    district: 'Platform Core',
    type: 'property',
    demand: 'medium',
    baseRent: 24,
    growth: 0.14,
    marketPrice: 345,
    flavor: 'If the system likes you, the month gets easier.',
  },
  {
    id: 10,
    name: 'Cloud Kitchens',
    district: 'Gig Belt',
    type: 'property',
    demand: 'medium',
    baseRent: 26,
    growth: 0.15,
    marketPrice: 362,
    flavor: 'Every shortcut still costs time.',
  },
  {
    id: 11,
    name: 'Venture Heights',
    district: 'Speculation',
    type: 'property',
    demand: 'high',
    baseRent: 35,
    growth: 0.22,
    marketPrice: 520,
    flavor: 'The rent assumes your startup already exited.',
  },
  {
    id: 12,
    name: 'Labor Board Shuffle',
    district: 'Bureaucracy',
    type: 'event',
    demand: 'medium',
    baseRent: 0,
    growth: 0,
    marketPrice: 0,
    flavor: 'Forms, queues, and a small chance of mercy.',
  },
  {
    id: 13,
    name: 'Warehouse Artist Den',
    district: 'Fringe',
    type: 'property',
    demand: 'low',
    baseRent: 18,
    growth: 0.1,
    marketPrice: 248,
    flavor: 'Good light, bad insulation, worse plumbing.',
  },
  {
    id: 14,
    name: 'Remote Work Commons',
    district: 'Hybrid',
    type: 'property',
    demand: 'medium',
    baseRent: 23,
    growth: 0.13,
    marketPrice: 318,
    flavor: 'Looks efficient until the Wi-Fi dies.',
  },
  {
    id: 15,
    name: 'Auction Block',
    district: 'Market',
    type: 'market',
    demand: 'high',
    baseRent: 0,
    growth: 0,
    marketPrice: 0,
    flavor: 'The market sells only when it smells desperation.',
  },
]

export const AI_ROSTER: Array<{
  id: string
  name: string
  color: string
  archetype: Archetype
  jobId: JobId
}> = [
  {
    id: 'nova',
    name: 'Nova',
    color: '#ff7b53',
    archetype: 'opportunist',
    jobId: 'freelance',
  },
  {
    id: 'mika',
    name: 'Mika',
    color: '#4c7df0',
    archetype: 'stability',
    jobId: 'retail',
  },
  {
    id: 'jules',
    name: 'Jules',
    color: '#2abf88',
    archetype: 'social',
    jobId: 'creator',
  },
  {
    id: 'sol',
    name: 'Sol',
    color: '#f2b632',
    archetype: 'asset-hunter',
    jobId: 'corporate',
  },
  {
    id: 'ria',
    name: 'Ria',
    color: '#9b6ef3',
    archetype: 'opportunist',
    jobId: 'creator',
  },
]

export const DEFAULT_CONFIG: GameConfig = {
  playerName: 'You',
  jobId: 'retail',
  totalRounds: 12,
  aiCount: 3,
}
